In [1]:
import numpy as np

from numpy import linalg as LA

In [2]:
def square_matrix_ridge_regression(X,Y,Astar,lmda,beeta):
    t=1+X.shape[1]
    D=lmda*np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
    C=lmda*Astar
    for s in range(1,t):
        xs=X[:,s-1]
        ys=Y[:,s-1]
        C=C+(1/beeta)*np.outer(ys,xs)
        D=D+(1/beeta)*np.outer(xs,xs)
    return C.dot(np.linalg.inv(D))

In [3]:
A=np.random.rand(2,4)
Astar=A+np.random.normal(0,np.sqrt(0.09),A.shape)

In [4]:
X=np.zeros((4,1000000))
Y=np.zeros((2,1000000))

In [5]:
for t in range(1000000):
    X[:,t]=np.random.rand(4)
    Y[:,t]=A.dot(X[:,t])+np.random.normal(0,np.sqrt(0.0001),2)

In [6]:
A_regression=square_matrix_ridge_regression(X,Y,Astar,100000,100000)

In [7]:
LA.norm((A-A_regression),'fro')

0.8181194925605013

In [8]:
print(A)

[[0.48658269 0.48976226 0.18014122 0.14207102]
 [0.21412302 0.52484233 0.24594365 0.82195844]]


In [9]:
print(A_regression)

[[0.1026787  0.96763586 0.33988832 0.11130353]
 [0.08642043 0.1312288  0.37072265 0.53858779]]


In [10]:
print(A-A_regression)

[[ 0.38390399 -0.47787359 -0.1597471   0.03076749]
 [ 0.12770259  0.39361352 -0.124779    0.28337066]]


In [11]:
print(Astar)

[[0.10268106 0.96764539 0.33989521 0.11130885]
 [0.08640237 0.13120854 0.37070669 0.53856842]]
